# Those tests are allowed to fail
name: experimental
on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  tinygo:
    name: tinygo 0.25.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: tinygo test ./...
        run: |
          docker run --rm -v $(pwd):/src -w /src tinygo/tinygo:0.25.0 tinygo test ./...
